#######################
FA vs B wingspan
#######################
Call:
lm(formula = FA ~ B, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-9.3048 -1.9322 -0.4651  1.4841 14.5491

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) 11.429465   1.550979   7.369 5.28e-12 ***
B            0.117876   0.005206  22.643  < 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.318 on 188 degrees of freedom
Multiple R-squared:  0.7317,	Adjusted R-squared:  0.7303
F-statistic: 512.7 on 1 and 188 DF,  p-value: < 2.2e-16

#########################
FA vs NL.W noseleaf width
##########################
lm(formula = FA ~ NL.W, data = allrhino58traits)

Residuals:
     Min       1Q   Median       3Q      Max
-10.0025  -2.8233  -0.9944   2.1592  10.2655

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)  22.0790     1.3955   15.82   <2e-16 ***
NL.W          2.6987     0.1533   17.60   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.937 on 188 degrees of freedom
Multiple R-squared:  0.6223,	Adjusted R-squared:  0.6203
F-statistic: 309.8 on 1 and 188 DF,  p-value: < 2.2e-16

############FA vs NL.W noseleaf width########
Call:
lm(formula = FA ~ NL.W, data = allrhino58traits)

Residuals:
     Min       1Q   Median       3Q      Max
-10.0025  -2.8233  -0.9944   2.1592  10.2655

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)  22.0790     1.3955   15.82   <2e-16 ***
NL.W          2.6987     0.1533   17.60   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.937 on 188 degrees of freedom
Multiple R-squared:  0.6223,	Adjusted R-squared:  0.6203
F-statistic: 309.8 on 1 and 188 DF,  p-value: < 2.2e-16

#####################
# ear length vs sella
######################
Call:
lm(formula = E ~ S.I, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-7.9738 -1.6084 -0.1454  1.4599  9.5762

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)  10.9853     0.4355   25.23   <2e-16 ***
S.I           2.3887     0.1021   23.40   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.568 on 188 degrees of freedom
Multiple R-squared:  0.7444,	Adjusted R-squared:  0.743
F-statistic: 547.5 on 1 and 188 DF,  p-value: < 2.2e-16

#### fmaxe vs ear length
Call:
lm(formula = FmaxE ~ E, data = allrhino58traits)

Residuals:
     Min       1Q   Median       3Q      Max
-31.1407  -6.4399   0.3495   7.4663  23.2158

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 152.6941     3.0922   49.38   <2e-16 ***
E            -3.7254     0.1485  -25.08   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 10.34 on 188 degrees of freedom
Multiple R-squared:  0.7699,	Adjusted R-squared:  0.7687
F-statistic: 629.1 on 1 and 188 DF,  p-value: < 2.2e-16

#### fmaxe vs sella
Call:
lm(formula = FmaxE ~ S.I, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-29.839  -4.626   0.599   7.880  41.330

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 116.3914     1.8722   62.17   <2e-16 ***
S.I         -10.0977     0.4389  -23.01   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 11.04 on 188 degrees of freedom
Multiple R-squared:  0.7379,	Adjusted R-squared:  0.7365
F-statistic: 529.3 on 1 and 188 DF,  p-value: < 2.2e-16

#### fmaxe vs FA
Call:
lm(formula = FmaxE ~ FA, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-40.037 -15.293   7.291  13.816  23.396

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 165.5513     9.4123  17.589   <2e-16 ***
FA           -1.9100     0.2022  -9.448   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 17.76 on 188 degrees of freedom
Multiple R-squared:  0.322,	Adjusted R-squared:  0.3184
F-statistic: 89.27 on 1 and 188 DF,  p-value: < 2.2e-16

#### fmaxe vs HB

Call:
lm(formula = FmaxE ~ HB, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-42.461 -12.996   8.499  14.347  21.907

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 142.0746     8.4570  16.800  < 2e-16 ***
HB           -1.3274     0.1715  -7.742 5.87e-13 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 18.78 on 188 degrees of freedom
Multiple R-squared:  0.2417,	Adjusted R-squared:  0.2377
F-statistic: 59.93 on 1 and 188 DF,  p-value: 5.875e-13


#### fmaxe vs M

Call:
lm(formula = FmaxE ~ M, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-52.470  -7.031   8.796  13.120  24.781

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  86.4157     2.8273  30.564  < 2e-16 ***
M            -0.9328     0.2490  -3.746 0.000238 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 20.8 on 188 degrees of freedom
Multiple R-squared:  0.06947,	Adjusted R-squared:  0.06452
F-statistic: 14.04 on 1 and 188 DF,  p-value: 0.0002384



#### fmaxe vs AR
Call:
lm(formula = FmaxE ~ AR, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-54.221 -11.040   5.695  12.593  29.394

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   90.095     10.208   8.826 7.46e-16 ***
AR            -1.957      1.562  -1.253    0.212    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 21.47 on 188 degrees of freedom
Multiple R-squared:  0.008278,	Adjusted R-squared:  0.003003
F-statistic: 1.569 on 1 and 188 DF,  p-value: 0.2119

#### fmaxe vs WL
Call:
lm(formula = FmaxE ~ WL, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-53.592 -10.511   5.531  10.991  28.369

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  76.3816     5.2414  14.573   <2e-16 ***
WL            0.1602     0.7446   0.215     0.83    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 21.56 on 188 degrees of freedom
Multiple R-squared:  0.0002462,	Adjusted R-squared:  -0.005072
F-statistic: 0.0463 on 1 and 188 DF,  p-value: 0.8299



#### fmaxe vs B


Call:
lm(formula = FmaxE ~ B, data = allrhino58traits)

Residuals:
   Min     1Q Median     3Q    Max
-47.40 -13.87   8.04  14.77  26.03

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept) 142.03264    8.88037  15.994  < 2e-16 ***
B            -0.21940    0.02981  -7.361 5.54e-12 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 19 on 188 degrees of freedom
Multiple R-squared:  0.2237,	Adjusted R-squared:  0.2196
F-statistic: 54.18 on 1 and 188 DF,  p-value: 5.539e-12


#### fmaxe vs lancet width

Call:
lm(formula = FmaxE ~ NL.W, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-42.248  -7.999   2.721  11.148  33.509

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 153.3812     5.1411   29.84   <2e-16 ***
NL.W         -8.5217     0.5648  -15.09   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 14.5 on 188 degrees of freedom
Multiple R-squared:  0.5477,	Adjusted R-squared:  0.5453
F-statistic: 227.6 on 1 and 188 DF,  p-value: < 2.2e-16


#### fmaxe vs lancet length


Call:
lm(formula = FmaxE ~ NL.L, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-40.123  -8.168   1.993  11.451  54.987

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 146.1989     5.2432   27.88   <2e-16 ***
NL.L         -5.3649     0.3998  -13.42   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 15.41 on 188 degrees of freedom
Multiple R-squared:  0.4892,	Adjusted R-squared:  0.4865
F-statistic: 180.1 on 1 and 188 DF,  p-value: < 2.2e-16


#### fmaxe vs INCW

Call:
lm(formula = FmaxE ~ INCW, data = allrhino58traits)

Residuals:
    Min      1Q  Median      3Q     Max
-33.691  -5.599   0.180   9.115  20.611

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  99.1500     1.3491   73.50   <2e-16 ***
INCW         -6.9780     0.3345  -20.86   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 11.84 on 188 degrees of freedom
Multiple R-squared:  0.6983,	Adjusted R-squared:  0.6967
F-statistic: 435.1 on 1 and 188 DF,  p-value: < 2.2e-16
